src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Content = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): static
    {
        $this->Content = $Content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->title;   
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class,[
                'attr' =>[
                    'class'=>'form-control',
                    'minlenght' =>'2',
                    'maxlenght' =>'200',
                ],
                'label'=>'Titre de l article',
                'label_attr' =>[
                    'class'=> 'form-label mt-3'
                ]
            ])
            ->add('Content', TextareaType::class,[
                'attr' =>[
                    'class'=>'form-control',
                ],
                'label'=>'Description',
                'label_attr' =>[
                    'class'=> 'form-label mt-3'
                ]
            ])
             ->add('image', 
             //FileType::class,
            // [
            //     'mapped' => false,
            //     'constraints' => [
            //         new File([
            //             'maxSize' => '2000k',
            //         ])
            //     ],
            // ]
            )

            ->add('user')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\Article1Type;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/article.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    

    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        $comments = $article->getComments();
        return $this->render('article/voirArticle.html.twig', [
            'article' => $article,
            'comments' => $comments
        ]);
    }

    
    
}

templates/article/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous les articles
{% endblock %}

{% block body %}

<div class="container">
	<div class="p-5 mb-4 bg-light rounded-3">
		<div class="container-fluid ">
			<h1 class="text-center mt-5 mb-5">Tous les articles</h1>
			<h5>La mode c'est pour qui?</h5>
			<p> On suit la mode pour signaler son appartenance à un groupe social, un groupe de pensée, une forme d’esthétisme, pour se distinguer des autres ; donc pour signaler son originalité, ses refus, ses rejets sociaux, politiques… La mode rassemble et rassure. Mais on peut aussi être à la mode par conformisme.</p>
		</div>
	</div>
<div class="row row-cols-1 row-cols-md-3 g-4 ">
		{% if articles|length  > 0 %}
		
			{% for article in articles %}
				<div class="col">
					<div class="card">
						<img src="{{ article.image }}" class="card-img-top img-fluid w-100" style="width: 15rem;" alt="image de la categorie">
						<div class="card-body">
							<h5 class="card-title">{{ article.title }}</h5>
							<p class="card-text">{{ article.category }}</p>
							<p class="card-text">{{ article.Content }}</p>
								<button type="button" class="btn btn-outline-dark">
									<a href="{{ path('app_article_show', {'id': article.id}) }}">Voir</a>
								</button>
							
						</div>
					</div>
				</div>	
			{% endfor %}	
			{% else %}
			<p> desolé aucun article </p>
				
		{% endif %}
	</div>

	
<div
{% endblock %}

templates/article/voirArticle.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les articles de mode
{% endblock %}

{% block body %}
	<div class="container">
		<h1>{{ article.title }}</h1>

		<div class="row">
			<div class="col sm-6">
				<div class="card mb-3">
					<img src="{{ article.image }}" class="card-img-top w-25" alt="image de l'article">
					<div class="card-body">
						<h5 class="card-title">{{ article.title }}</h5>
						<p class="card-text">{{ article.category }}</p>
						<p class="card-text">{{ article.content }}</p>
					</div>
				</div>
				<button type="button" class="btn btn-outline-dark mb-5">
						 <a href="{{ path('app_article_index') }}">Voir tous les articles</a>
				</button>
               
			</div>
			


			<div class="col sm-6">
				<div class="card border-secondary mb-3" style="max-width: 35rem;">
					<div class="card-header">Commentaire</div>
					<div class="card-body text-secondary">
						{% for comment in comments %}
							<ul class="list-group list-group-flush">
								<li class="list-group-item">{{ comment.user.pseudo }}
									a dit:
									{{ comment.content }}</li>
							</ul>
						{% endfor %}
					</div>
					{# ici je recupere l'id de larticle et je le passe dans le lien  #}
					<button type="button" class="btn btn-outline-dark">
						<a href="{{ path('app_comment_new',{'id': article.id}) }}">
							Ajouter un commentaire
						</a>
					</button>
					

				</div>
			</div>
		</div>
	</div>
{% endblock %}